version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - ng build --configuration production

  post_build:
    commands:
      - aws s3 sync dist/landing-ottokare/browser s3://landing-ottokare-samirt --delete
      - aws cloudfront create-invalidation --distribution-id E265TYHO93ZEZ2 --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/landing-ottokare/browser'